### PR TITLE
Header Fixes - Menu flyout image Fix

### PR DESCRIPTION
**Pull request by SnehAras**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--{repo}--{owner}.hlx.live/
- After: https://feature-metafox-header-fixes--metafox-sites--bmw-importer.hlx.page/master/en/reference/backgroundmedia#

### CODE REVIEW

**Comment by AmolYPatil** [comment]
https://feature-ecid-duplicate-call--metafox-sites--bmw-importer.hlx.page/master/en/reference/iframe-component

**Review by AmolYPatil — APPROVED** [review]
Approved

**Comment by manish11665313** [comment]
this is giving issue on normal 1280 mode in 1st flyout the image size is bigger

**Review by ChaitanyaSravanthi-Ch — APPROVED** [review]

**Comment by manish11665313** [comment]
Closing this PR since we already have the duplicate PR

**Pull request closed without merging**
